# Generated by Django 4.0 on 2022-02-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('show_link', models.BooleanField(default=False)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('header', models.CharField(blank=True, max_length=100)),
                ('is_test', models.BooleanField(default=False)),
                ('to_all_users', models.BooleanField(default=False)),
                ('to', models.TextField(blank=True)),
                ('template', models.CharField(choices=[('email/email.html', 'General'), ('verify_email.html', 'Verify email'), ('reset_password.html', 'Reset password')], default='General', max_length=100)),
                ('programed_send_date', models.DateTimeField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('was_sent', models.BooleanField(default=False, editable=False)),
                ('blocks', models.ManyToManyField(related_name='blocks', to='Emails.Block')),
            ],
        ),
    ]
