# Generated by Django 4.0 on 2022-03-30 21:10

import App.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='Users.user')),
                ('nickname', models.CharField(blank=True, error_messages={'unique': 'This nickname already exists.'}, max_length=50, null=True, unique=True, verbose_name='Nick')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=App.storage.image_file_upload, verbose_name='Profile image')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Non-binary'), ('P', 'Prefer not to say')], default='P', max_length=1, null=True, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
        ),
    ]
