# Generated by Django 4.1.1 on 2022-09-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("facebook", "Facebook"),
                    ("google", "Google"),
                    ("twitter", "Twitter"),
                ],
                default="email",
                max_length=10,
                null=True,
                verbose_name="Auth provider",
            ),
        ),
    ]
