# Generated by Django 4.0.6 on 2022-08-08 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractEmailClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, null=True)),
                ('affair', models.CharField(choices=[('NOTIFICATION', 'Notification'), ('PROMOTION', 'Promotion'), ('GENERAL', 'General'), ('SETTINGS', 'Settings'), ('INVOICE', 'Invoice'), ('SUGGESTION', 'Suggestion')], default='NOTIFICATION', max_length=100)),
                ('sent_date', models.DateTimeField(null=True)),
                ('was_sent', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('show_link', models.BooleanField(default=False)),
                ('link_text', models.CharField(max_length=100, null=True)),
                ('link', models.URLField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('abstractemailclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Emails.abstractemailclass')),
                ('subject', models.CharField(max_length=100)),
                ('is_test', models.BooleanField(default=False)),
                ('programed_send_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Emails.abstractemailclass',),
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affairs', django_mysql.models.ListCharField(models.CharField(choices=[('NOTIFICATION', 'Notification'), ('PROMOTION', 'Promotion'), ('GENERAL', 'General'), ('SETTINGS', 'Settings'), ('INVOICE', 'Invoice'), ('SUGGESTION', 'Suggestion')], default='GENERAL', max_length=15), max_length=79, size=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='abstractemailclass',
            name='blocks',
            field=models.ManyToManyField(related_name='%(class)s_blocks', to='Emails.block'),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('abstractemailclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Emails.abstractemailclass')),
                ('subject', models.CharField(choices=[('SUGGESTION', 'Suggestion'), ('BUG', 'Bug'), ('ERROR', 'Error'), ('OTHER', 'Other')], default='SUGGESTION', max_length=100)),
                ('was_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('Emails.abstractemailclass',),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('abstractemailclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Emails.abstractemailclass')),
                ('subject', models.CharField(max_length=100)),
                ('is_test', models.BooleanField(default=False)),
                ('programed_send_date', models.DateTimeField(null=True)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('Emails.abstractemailclass',),
        ),
    ]
